version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: contenedor_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mi_base
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: ./app
    container_name: contenedor_flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
